# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Executes Swiftlint and Unit Tests"
  lane :lint_and_tests do
    lint
    tests
  end

  desc "Run SwiftLint"
  lane :lint do
    swiftlint(
      strict: true,
      raise_if_swiftlint_error: true
    )
  end

  desc "Executes Unit Tests"
  lane :tests do
    run_tests(
      scheme: "CDCI",
      destination: "platform=iOS Simulator,name=iPhone 16 Pro,arch=arm64"
    )
  end
end
