name: Build, lint and test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Select Xcode 16.3
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install fastlane
        run: gem install fastlane

      # - name: Install SwiftLint
      #   run: brew install swiftlint

      - name: Resolve Swift Packages
        run: swift package resolve

      - name: Run lint and tests
        run: fastlane lint_and_tests