name: Build, lint and test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Select Xcode 16.3
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Create Gemfile with SwiftLint plugin
        run: |
          echo 'source "https://rubygems.org"' > Gemfile
          echo 'gem "fastlane"' >> Gemfile
          echo 'gem "fastlane-plugin-swiftlint"' >> Gemfile

      - name: Install dependencies
        run: bundle install

      - name: Install SwiftLint via brew
        run: brew install swiftlint

      - name: Run Fastlane lint and tests
        run: bundle exec fastlane lint_and_tests